### ISSUE TITLE
Ability to use action annotations in a separate class without database annotation

### ISSUE THREAD

**Issue by mertkokusen** [simolus3/tinano#10]
Hi,

As far as I understand in the current implementation all of the action annotated (Update, Select...) methods have to be in a database class annotated as a database. 
How about generating repository classes that keep a reference to the database class and including the methods in these classes? I haven't tried this but from the code it seems like it wouldn't work. Do you have any suggestions? Is it possible some how?

**Comment by simolus3** [comment]
Let's see, maybe we could have an API similar to this:
```dart
@repository
abstract class UserRepository {
  @Select("SELECT * FROM users WHERE name = ?")
  Future<User> loadUserByName(String name);
}

@TinanoDb(...)
abstract class Database {
  // ...
  UserRepository get users;
}
```
And have tinano generate the correct binding in the `open` method. Is this what you want?

**Comment by mertkokusen** [comment]
This is pretty close to what was in my mind :) @repository annotation is exactly on point, I just imagined the reference would be the other way around, like injecting a database reference into the repository class, but this may do as well.

**Comment by simolus3** [comment]
I've just published [moor](https://github.com/simolus3/moor/) to replace this library. It supports this feature, pretty similar to the code snippet above.
