### ISSUE TITLE
missing type

### ISSUE THREAD

**Issue by ralph-bergmann** [simolus3/tinano#3]
Please do the following change in `builder.dart`

from
   `DatabaseBuilder doOnCreate(OnDatabaseCreateFn fn) {`
to
   `DatabaseBuilder<T> doOnCreate<T>(OnDatabaseCreateFn fn) {`

**Comment by simolus3** [comment]
Good call, thanks for pointing this out. I'm currently working on some major changes of this library that are going to deprecate that whole `DatabaseBuilder` mechanism in favor of directly writing `@onCreate` and `@onUpgrade` annotated methods in your database class, that's also going to fix this.
